
server {
    server_tokens off;
    listen 80;
    error_log  /dev/stderr;
    access_log /dev/stdout;
    root /var/www/html/;

    location / {
        try_files $uri /index.php?$args;
    }

    location /static/ {
        try_files $uri $uri/;
    }

    location ~ \.php$ {
        root /var/www/html/demo/;
        fastcgi_pass flatcms-backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include /etc/nginx/fastcgi_params;
    }
}
